version: "3.1"
services:
        #elasticsearch:
        #        image: elasticsearch:7.6.2
        #        ports:
        #                - 9200:9200

        #       environment:
        #                - "discovery.type=single-node"
        #        volumes:
        #                - /home/krishna/esdata:/usr/share/elasticsearch/data

        stack:
                build: .
                ports:
                        - 8000:8000
                volumes:
                        - /home/krishna/models:/app/models
